ARG NODE_VERSION=18
ARG CLIENT_PORT=3000
ARG SERVER_PORT=3001
ARG EXTERNAL_SERVER_URL=http://localhost:3001

FROM node:$NODE_VERSION-buster as base

WORKDIR /app

FROM base as builder

ARG EXTERNAL_SERVER_URL
ARG SERVER_PORT

ENV EXTERNAL_SERVER_URL=$EXTERNAL_SERVER_URL
ENV INTERNAL_SERVER_URL=http://server:${SERVER_PORT}

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

COPY . .

RUN yarn lerna bootstrap
RUN rm -rf /app/packages/client/dist/ && yarn build --scope=client

FROM node:$NODE_VERSION-buster-slim as production

ARG CLIENT_PORT

WORKDIR /app

COPY --from=builder /app/packages/client/dist/ /app/dist/
COPY --from=builder /app/packages/client/server/ /app/server/
COPY --from=builder /app/packages/client/package.json /app/package.json
RUN yarn install --production=true

ENV CLIENT_PORT=$CLIENT_PORT

EXPOSE $CLIENT_PORT
CMD [ "node", "/app/server/index.js" ]
